// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // static const clientIDWeb = '414429242328-kpmrn64ieptf0qavqduaolu1kl6eis15.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXiwOUNsbzKH7sbSAZrqA9f7VOeCMdUOQ',
    appId: '1:414429242328:web:a4685f5ac6895ea767c8ad',
    messagingSenderId: '414429242328',
    projectId: 'gigaturnip-b6b5b',
    authDomain: 'gigaturnip-b6b5b.firebaseapp.com',
    storageBucket: 'gigaturnip-b6b5b.appspot.com',
    measurementId: 'G-Y8JTEJMTET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvPwWECwMSkjp4-MCOYFInHWGpYWk1Cuo',
    appId: '1:414429242328:android:77b1305db9bae70f67c8ad',
    messagingSenderId: '414429242328',
    projectId: 'gigaturnip-b6b5b',
    storageBucket: 'gigaturnip-b6b5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcJn7yWnVMu9PCz2fKnyAstWRbykLbvsU',
    appId: '1:414429242328:ios:38a34e6fdfe923ec67c8ad',
    messagingSenderId: '414429242328',
    projectId: 'gigaturnip-b6b5b',
    storageBucket: 'gigaturnip-b6b5b.appspot.com',
    androidClientId: '414429242328-7alrfsifff7n6m7ot6lf15jrub86b5ag.apps.googleusercontent.com',
    iosClientId: '414429242328-4arrplodtdo5uo1ftg03dnht406sgg6t.apps.googleusercontent.com',
    iosBundleId: 'io.kloop.gigaturnip',
  );
}
